theme: jekyll-theme-cayman
title: Madeleine J. Zurowski
baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://mjzurowski.github.io" # change this to the base hostname & protocol for your site

target-blank:
    rel: nofollow

header_page_refs: [home,about,research,outreach,dm,reading]


