# theme: jekyll-theme-slate
theme: jekyll-theme-cayman
title: Madeleine J. Zurowski
google-site-verification: kTg4RbjusJd8hpUI0SjMXfWVJFLz0mbxyBhVFh7NzZ0

header_pages:
  - about.md
  - research-outputs.md
  - outreach.md
  - dm.md

